### PR TITLE
Tomlink enable autovacuum

### PR DESCRIPTION
**Pull request by tmlink**
Please review  @vitroth

### CODE REVIEW

**Comment by vitroth** [comment]
This PR is against the wrong repo.  Change to against master in this repo instead of master in krobertson's repo.  (Which is why the diff is more then your changes.)

**Comment by tmlink** [comment]
How would that have possibly happened?

**Comment by vitroth** [comment]
because the apcera/chef-postgres repo was forked from krobertson/chef-postgres, and the default pull request UI generates PRs against the upstream fork.

**Comment by tmlink** [comment]
should I have:

      git checkout -b tomlink_enable_autovacuum apcera/chef-postgresql

or:

      git push -o apcera/chef-postgresql tomlink_enable_autovacuum


How should I have noticed this before I pushed to the wrong repo?

**Comment by vitroth** [comment]
You didn't push to the wrong repo, but your pull request is between krobertson:master and apcera:tomlink_enable_autovacuum.  It should be between apcera:master and apcera:tomlink_enable_autovacuum. 

Delete this PR, create a new one and when creating change the base fork to the apcera repo

**Comment by tmlink** [comment]
No mention of which repo I was working against

Tom

$ git status
On branch tomlink_enable_autovacuum
Your branch is up-to-date with 'origin/tomlink_enable_autovacuum'.
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

new file:   .gitattributes
modified:   attributes/default.rb
modified:   templates/default/postgresql.conf.standard.erb

thomaslink at Thomass-MacBook-Pro in ~/go/src/
github.com/apcera/chef-postgresql on tomlink_enable_autovacuum*
$ git diff
thomaslink at Thomass-MacBook-Pro in ~/go/src/
github.com/apcera/chef-postgresql on tomlink_enable_autovacuum*
$ git commit
[tomlink_enable_autovacuum 90a7f1c] enabling the setting of some postgresql
settings related to autovacuum and checkpointing
 3 files changed, 10 insertions(+), 6 deletions(-)
 create mode 100644 .gitattributes
thomaslink at Thomass-MacBook-Pro in ~/go/src/
github.com/apcera/chef-postgresql on tomlink_enable_autovacuum△
$ git log
commit 90a7f1ce99f211d0748c3546562524d1f0ffef9b
Author: Tom Link <tom.link@apcera.com>
Date:   Thu May 7 12:45:12 2015 -0700

    enabling the setting of some postgresql settings related to
    autovacuum and checkpointing

commit b261ce25ec4541134b0f5b0f50bf5815d59adc70
Author: Tom Link <tom.link@apcera.com>
Date:   Mon Apr 20 15:46:29 2015 -0400

    Enable lines in the postgres configuration files for
    auto_vacuum and track_counts
    if the appropriate values are set in chef.   i
    This is needed to enable autovacuum.

commit eb447f1afcf56ed1399856981330faf2bbcae6cd
Merge: 6c7fac6 84d1afb
Author: David Nolan <david@apcera.com>
Date:   Wed Apr 1 12:29:03 2015 -0700

    Merge pull request #1 from apcera/use-replication-connection-string

    Use the replication connection string when doing the initial
duplication for replication.

commit 84d1afb80e15d876b0cf15fc15d48d679a0c8486
Author: David Nolan <david@apcera.com>
thomaslink at Thomass-MacBook-Pro in ~/go/src/
github.com/apcera/chef-postgresql on tomlink_enable_autovacuum△
$ git push -u origin tomlink_enable_autovacuum
Counting objects: 63, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (35/35), done.
Writing objects: 100% (63/63), 9.16 KiB | 0 bytes/s, done.
Total 63 (delta 38), reused 39 (delta 20)
To ssh://git@github.com/apcera/chef-postgresql.git
 * [new branch]      tomlink_enable_autovacuum -> tomlink_enable_autovacuum
Branch tomlink_enable_autovacuum set up to track remote branch
tomlink_enable_autovacuum from origin.
thomaslink at Thomass-MacBook-Pro in ~/go/src/
github.com/apcera/chef-postgresql on tomlink_enable_autovacuum
$ git status
On branch tomlink_enable_autovacuum
Your branch is up-to-date with 'origin/tomlink_enable_autovacuum'.
nothing to commit, working directory clean

**Pull request closed without merging**
